#!/bin/bash

CONFIG=/home/tor/.wifi_manager/\"Big_Black_Fast_Skate\".conf
# CONFIG=/home/tor/.scripts/wifi_configs/home.conf

sudo killall wpa_supplicant
sudo rm -f /var/run/wpa_supplicant/wlo1
if [[ $1 = "" ]]; then
	echo "using $CONFIG";
	sudo wpa_supplicant -i wlo1 -c $CONFIG -B
	sudo ifconfig wlo1 192.168.0.3 netmask 255.255.255.0
	sudo route add default gw 192.168.0.1 wlo1
else
	echo "using "$1;
	sudo wpa_supplicant -i wlo1 -c $1 -B
	sudo dhcpcd --waitip 4 wlo1
fi
