#!/usr/bin/fish
xinput set-prop 'Razer  Razer Abyssus' 'Coordinate Transformation Matrix' 0.3 0 0 0 0.3 0 0 0 1
env DISPLAY=:8 xinput set-prop 'Razer  Razer Abyssus' 'Coordinate Transformation Matrix' 1 0 0 0 1 0 0 0 1

